@todoapi_HostAddress = https://localhost:7059

GET {{todoapi_HostAddress}}/listtasks

###

GET {{todoapi_HostAddress}}/users

###

POST {{todoapi_HostAddress}}/account/listtasks
Content-Type: application/json

{
  "username": "zxczx",
  "password": "dfsfds"
}

###

POST {{todoapi_HostAddress}}/user/register
Content-Type: application/json

{
  "username": "zxczx",
  "password": "dfsfds"
}

###

POST {{todoapi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name": "My First Task"
}

###

POST {{todoapi_HostAddress}}/account/addtask
Content-Type: application/json

{
  "username": "zxczx",
  "password": "dfsfds"
}
###

PATCH {{todoapi_HostAddress}}/tick/{{id}}

###

@id=8
