@todoapi_HostAddress = https://localhost:7059

POST {{todoapi_HostAddress}}/listtasks
Content-Type: application/json
{

}
###

POST {{todoapi_HostAddress}}/listtasks?sorting=oldest
Content-Type: application/json

{
  "username": "zxczx",
  "password": "dfsfds"
}

###

POST {{todoapi_HostAddress}}/deletetask/5
Content-Type: application/json
{
    "username": "zxczx",
    "password": "dfsfds"
}
###

POST {{todoapi_HostAddress}}/taskinfo/1
Content-Type: application/json

{
    "username": "zxczx",
    "password": "dfsfds"
}

###

POST {{todoapi_HostAddress}}/addtask
Content-Type: application/json

{
  "name": "public"
}

###

POST {{todoapi_HostAddress}}/addchildtask/10
Content-Type: application/json

{
  "username": "zxczx",
  "password": "dfsfds",
  "name": "c2"
}

###

POST {{todoapi_HostAddress}}/user/register
Content-Type: application/json

{
  "username": "empty",
  "password": ""
}

###

PATCH {{todoapi_HostAddress}}/edittask/5
Content-Type: application/json
{
    "username": "zxczx",
    "password": "dfsfds",
    "name": "edited task",
    "parentTaskId": "6"
}
###

PATCH {{todoapi_HostAddress}}/ticktask/11
Content-Type: application/json
{
    "username": "zxczx",
    "password": "dfsfds"
}
###

@id=1
